// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Radio_WebApi.Data;

namespace Radio_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210820025446_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Radio_WebAPI.Models.Albuns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Albuns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 1990,
                            Imagem = "",
                            Nome = "Classicos"
                        },
                        new
                        {
                            Id = 2,
                            Ano = 1978,
                            Imagem = "",
                            Nome = "MPB"
                        });
                });

            modelBuilder.Entity("Radio_WebAPI.Models.AlbunsInterpretes", b =>
                {
                    b.Property<int>("AlbunsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterpretesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlbunsId", "InterpretesId");

                    b.HasIndex("InterpretesId");

                    b.ToTable("AlbunsInterpretes");

                    b.HasData(
                        new
                        {
                            AlbunsId = 1,
                            InterpretesId = 1
                        },
                        new
                        {
                            AlbunsId = 2,
                            InterpretesId = 2
                        },
                        new
                        {
                            AlbunsId = 2,
                            InterpretesId = 3
                        });
                });

            modelBuilder.Entity("Radio_WebAPI.Models.Interpretes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Interpretes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Roberto Carlos"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Toquinho"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Vinícius de Morais"
                        });
                });

            modelBuilder.Entity("Radio_WebAPI.Models.Musicas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estilo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<double>("Tempo")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Musicas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 1983,
                            Estilo = 1,
                            Nome = "Aquarela",
                            Tempo = 4.2000000000000002
                        },
                        new
                        {
                            Id = 2,
                            Ano = 1963,
                            Estilo = 1,
                            Nome = "Garota de Ipanema",
                            Tempo = 5.3499999999999996
                        },
                        new
                        {
                            Id = 3,
                            Ano = 2021,
                            Estilo = 2,
                            Nome = "Esse cara sou eu",
                            Tempo = 4.5300000000000002
                        },
                        new
                        {
                            Id = 4,
                            Ano = 1973,
                            Estilo = 2,
                            Nome = "Detalhes",
                            Tempo = 5.5999999999999996
                        });
                });

            modelBuilder.Entity("Radio_WebAPI.Models.MusicasInterpretes", b =>
                {
                    b.Property<int>("MusicasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterpretesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MusicasId", "InterpretesId");

                    b.HasIndex("InterpretesId");

                    b.ToTable("MusicasInterpretes");

                    b.HasData(
                        new
                        {
                            MusicasId = 1,
                            InterpretesId = 2
                        },
                        new
                        {
                            MusicasId = 2,
                            InterpretesId = 3
                        },
                        new
                        {
                            MusicasId = 3,
                            InterpretesId = 1
                        },
                        new
                        {
                            MusicasId = 4,
                            InterpretesId = 1
                        });
                });

            modelBuilder.Entity("Radio_WebAPI.Models.AlbunsInterpretes", b =>
                {
                    b.HasOne("Radio_WebAPI.Models.Albuns", "Albuns")
                        .WithMany("AlbunsInterpretes")
                        .HasForeignKey("AlbunsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Radio_WebAPI.Models.Interpretes", "Interpretes")
                        .WithMany("AlbunsInterpretes")
                        .HasForeignKey("InterpretesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Albuns");

                    b.Navigation("Interpretes");
                });

            modelBuilder.Entity("Radio_WebAPI.Models.MusicasInterpretes", b =>
                {
                    b.HasOne("Radio_WebAPI.Models.Interpretes", "Interpretes")
                        .WithMany("MusicasInterpretes")
                        .HasForeignKey("InterpretesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Radio_WebAPI.Models.Musicas", "Musicas")
                        .WithMany("MusicasInterpretes")
                        .HasForeignKey("MusicasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interpretes");

                    b.Navigation("Musicas");
                });

            modelBuilder.Entity("Radio_WebAPI.Models.Albuns", b =>
                {
                    b.Navigation("AlbunsInterpretes");
                });

            modelBuilder.Entity("Radio_WebAPI.Models.Interpretes", b =>
                {
                    b.Navigation("AlbunsInterpretes");

                    b.Navigation("MusicasInterpretes");
                });

            modelBuilder.Entity("Radio_WebAPI.Models.Musicas", b =>
                {
                    b.Navigation("MusicasInterpretes");
                });
#pragma warning restore 612, 618
        }
    }
}
